/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Appointment: typeof import('./../src/components/appointment.vue')['default']
    Card: typeof import('./../src/components/card.vue')['default']
    Carousel: typeof import('./../src/components/Carousel/index.vue')['default']
    CarouselItem: typeof import('./../src/components/Carousel/Item.vue')['default']
    Contactus: typeof import('../src/components/contactus.vuetus.vue')['default']
    ContactUs: typeof import('./../src/components/ContactUs.vue')['default']
    FileUpload: typeof import('./../src/components/fileUpload.vue')['default']
    LayoutFooter: typeof import('./../src/components/layout/footer.vue')['default']
    LayoutFooterFooter: typeof import('./../src/components/layout/footer/footer.vue')['default']
    LayoutHeader: typeof import('./../src/components/layout/header/index.vue')['default']
    LayoutHeaderMenuItem: typeof import('./../src/components/layout/header/MenuItem.vue')['default']
    LayoutHeaderServiceMenu: typeof import('./../src/components/layout/header/ServiceMenu.vue')['default']
    LayoutJumbotron: typeof import('./../src/components/layout/jumbotron.vue')['default']
    LayoutTheFooter: typeof import('./../src/components/layout/theFooter.vue')['default']
    LayoutTheHeader: typeof import('./../src/components/layout/theHeader.vue')['default']
    Principles: typeof import('./../src/components/principles.vue')['default']
    PrivacyPolicy: typeof import('./../src/components/privacyPolicy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Services: typeof import('./../src/components/services.vue')['default']
    Subscribe: typeof import('./../src/components/subscribe.vue')['default']
    TermAndConditions: typeof import('./../src/components/termAndConditions.vue')['default']
    VModal: typeof import('./../src/components/VModal/index.vue')['default']
    ZLink: typeof import('./../src/components/ZLink.vue')['default']
  }
}
