/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Appointment: typeof import('./../src/components/appointment.vue')['default']
    Contactus: typeof import('./../src/components/contactus.vue')['default']
    Ethos: typeof import('./../src/components/ethos.vue')['default']
    LayoutJumbotron: typeof import('./../src/components/layout/jumbotron.vue')['default']
    LayoutTheFooter: typeof import('./../src/components/layout/theFooter.vue')['default']
    LayoutTheHeader: typeof import('./../src/components/layout/theHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Services: typeof import('./../src/components/services.vue')['default']
    Subscribe: typeof import('./../src/components/subscribe.vue')['default']
  }
}
